<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>MAItems.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="MAItems.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.72" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.3" />
  </ItemGroup>

</Project>