using Microsoft.Data.Sqlite;
using System.Collections.Generic;

namespace MAItems.Database
{
    public class FinancialRepository
    {
        private readonly DatabaseContext _context;

        public FinancialRepository(DatabaseContext context)
        {
            _context = context;
        }

        public CompanyProfile? GetCompanyProfile(long dealId)
        {
            using var conn = _context.GetConnection();
            using var cmd = new SqliteCommand("SELECT * FROM CompanyProfiles WHERE DealId = @DealId;", conn);
            cmd.Parameters.AddWithValue("@DealId", dealId);
            using var reader = cmd.ExecuteReader();
            return reader.Read() ? MapCompanyProfile(reader) : null;
        }

        public void UpsertCompanyProfile(CompanyProfile p)
        {
            using var conn = _context.GetConnection();
            string sql = @"INSERT INTO CompanyProfiles (DealId, CompanyName, CompanyNameSub, HeadOfficeAddress, FactoryAddress, OtherOffice, Founded, Founded2, Capital, RepresentativeName, RepresentativeProfile, ShareholderInfo, BusinessDetail, Revenue, Employees, MainClients, MainSuppliers, Certifications, GroupCompanies, TransferReason, Remarks) VALUES (@DealId, @CompanyName, @CompanyNameSub, @HeadOfficeAddress, @FactoryAddress, @OtherOffice, @Founded, @Founded2, @Capital, @RepresentativeName, @RepresentativeProfile, @ShareholderInfo, @BusinessDetail, @Revenue, @Employees, @MainClients, @MainSuppliers, @Certifications, @GroupCompanies, @TransferReason, @Remarks) ON CONFLICT(DealId) DO UPDATE SET CompanyName=excluded.CompanyName, CompanyNameSub=excluded.CompanyNameSub, HeadOfficeAddress=excluded.HeadOfficeAddress, FactoryAddress=excluded.FactoryAddress, OtherOffice=excluded.OtherOffice, Founded=excluded.Founded, Founded2=excluded.Founded2, Capital=excluded.Capital, RepresentativeName=excluded.RepresentativeName, RepresentativeProfile=excluded.RepresentativeProfile, ShareholderInfo=excluded.ShareholderInfo, BusinessDetail=excluded.BusinessDetail, Revenue=excluded.Revenue, Employees=excluded.Employees, MainClients=excluded.MainClients, MainSuppliers=excluded.MainSuppliers, Certifications=excluded.Certifications, GroupCompanies=excluded.GroupCompanies, TransferReason=excluded.TransferReason, Remarks=excluded.Remarks;";
            using var cmd = new SqliteCommand(sql, conn);
            cmd.Parameters.AddWithValue("@DealId", p.DealId); cmd.Parameters.AddWithValue("@CompanyName", p.CompanyName); cmd.Parameters.AddWithValue("@CompanyNameSub", p.CompanyNameSub); cmd.Parameters.AddWithValue("@HeadOfficeAddress", p.HeadOfficeAddress); cmd.Parameters.AddWithValue("@FactoryAddress", p.FactoryAddress); cmd.Parameters.AddWithValue("@OtherOffice", p.OtherOffice); cmd.Parameters.AddWithValue("@Founded", p.Founded); cmd.Parameters.AddWithValue("@Founded2", p.Founded2); cmd.Parameters.AddWithValue("@Capital", p.Capital); cmd.Parameters.AddWithValue("@RepresentativeName", p.RepresentativeName); cmd.Parameters.AddWithValue("@RepresentativeProfile", p.RepresentativeProfile); cmd.Parameters.AddWithValue("@ShareholderInfo", p.ShareholderInfo); cmd.Parameters.AddWithValue("@BusinessDetail", p.BusinessDetail); cmd.Parameters.AddWithValue("@Revenue", p.Revenue); cmd.Parameters.AddWithValue("@Employees", p.Employees); cmd.Parameters.AddWithValue("@MainClients", p.MainClients); cmd.Parameters.AddWithValue("@MainSuppliers", p.MainSuppliers); cmd.Parameters.AddWithValue("@Certifications", p.Certifications); cmd.Parameters.AddWithValue("@GroupCompanies", p.GroupCompanies); cmd.Parameters.AddWithValue("@TransferReason", p.TransferReason); cmd.Parameters.AddWithValue("@Remarks", p.Remarks);
            cmd.ExecuteNonQuery();
        }

        public List<FinancialHighlight> GetFinancialHighlights(long dealId)
        {
            var list = new List<FinancialHighlight>();
            using var conn = _context.GetConnection();
            using var cmd = new SqliteCommand("SELECT * FROM FinancialHighlights WHERE DealId = @DealId ORDER BY PeriodType DESC, PeriodOrder ASC;", conn);
            cmd.Parameters.AddWithValue("@DealId", dealId);
            using var reader = cmd.ExecuteReader();
            while (reader.Read()) list.Add(MapFinancialHighlight(reader));
            return list;
        }

        public void UpsertFinancialHighlight(FinancialHighlight f)
        {
            using var conn = _context.GetConnection();
            string sql = @"INSERT INTO FinancialHighlights (DealId, PeriodType, PeriodOrder, PeriodLabel, Revenue, CostRate, GrossProfit, GrossProfitRate, SGA, OperatingProfit, OperatingProfitRate, OrdinaryProfit, NetIncome, EBITDA, Depreciation, CapEx, CurrentAssets, CashEquivalents, AccountsReceivable, Inventory, OtherCurrentAssets, FixedAssets, TotalAssets, CurrentLiabilities, AccountsPayable, ShortTermDebt, OtherCurrentLiabilities, FixedLiabilities, LongTermDebt, OtherFixedLiabilities, TotalLiabilities, NetAssets, RetainedEarnings) VALUES (@DealId, @PeriodType, @PeriodOrder, @PeriodLabel, @Revenue, @CostRate, @GrossProfit, @GrossProfitRate, @SGA, @OperatingProfit, @OperatingProfitRate, @OrdinaryProfit, @NetIncome, @EBITDA, @Depreciation, @CapEx, @CurrentAssets, @CashEquivalents, @AccountsReceivable, @Inventory, @OtherCurrentAssets, @FixedAssets, @TotalAssets, @CurrentLiabilities, @AccountsPayable, @ShortTermDebt, @OtherCurrentLiabilities, @FixedLiabilities, @LongTermDebt, @OtherFixedLiabilities, @TotalLiabilities, @NetAssets, @RetainedEarnings) ON CONFLICT(DealId, PeriodType, PeriodOrder) DO UPDATE SET PeriodLabel=excluded.PeriodLabel, Revenue=excluded.Revenue, CostRate=excluded.CostRate, GrossProfit=excluded.GrossProfit, GrossProfitRate=excluded.GrossProfitRate, SGA=excluded.SGA, OperatingProfit=excluded.OperatingProfit, OperatingProfitRate=excluded.OperatingProfitRate, OrdinaryProfit=excluded.OrdinaryProfit, NetIncome=excluded.NetIncome, EBITDA=excluded.EBITDA, Depreciation=excluded.Depreciation, CapEx=excluded.CapEx, CurrentAssets=excluded.CurrentAssets, CashEquivalents=excluded.CashEquivalents, AccountsReceivable=excluded.AccountsReceivable, Inventory=excluded.Inventory, OtherCurrentAssets=excluded.OtherCurrentAssets, FixedAssets=excluded.FixedAssets, TotalAssets=excluded.TotalAssets, CurrentLiabilities=excluded.CurrentLiabilities, AccountsPayable=excluded.AccountsPayable, ShortTermDebt=excluded.ShortTermDebt, OtherCurrentLiabilities=excluded.OtherCurrentLiabilities, FixedLiabilities=excluded.FixedLiabilities, LongTermDebt=excluded.LongTermDebt, OtherFixedLiabilities=excluded.OtherFixedLiabilities, TotalLiabilities=excluded.TotalLiabilities, NetAssets=excluded.NetAssets, RetainedEarnings=excluded.RetainedEarnings;";
            using var cmd = new SqliteCommand(sql, conn);
            BindFinancialHighlight(cmd, f);
            cmd.ExecuteNonQuery();
        }

        public ValuationData? GetValuationData(long dealId)
        {
            using var conn = _context.GetConnection();
            using var cmd = new SqliteCommand("SELECT * FROM ValuationData WHERE DealId = @DealId;", conn);
            cmd.Parameters.AddWithValue("@DealId", dealId);
            using var reader = cmd.ExecuteReader();
            return reader.Read() ? MapValuationData(reader) : null;
        }

        public void UpsertValuationData(ValuationData v)
        {
            using var conn = _context.GetConnection();
            string sql = @"INSERT INTO ValuationData (DealId, NetAssetValue, NetAssetNote, EBITDABase, EBITDABaseYear, EBITDAMultiple, EBITDANetCashDebt, EBITDANote, DCFDiscountRate, DCFTerminalGrowth, DCFEV, DCFNetCashDebt, DCFNote, NOI, CapRate, DirectNetCashDebt, DirectNote, EBITDAEquityValue, DCFEquityValue, DirectEquityValue, ValuationNote) VALUES (@DealId, @NetAssetValue, @NetAssetNote, @EBITDABase, @EBITDABaseYear, @EBITDAMultiple, @EBITDANetCashDebt, @EBITDANote, @DCFDiscountRate, @DCFTerminalGrowth, @DCFEV, @DCFNetCashDebt, @DCFNote, @NOI, @CapRate, @DirectNetCashDebt, @DirectNote, @EBITDAEquityValue, @DCFEquityValue, @DirectEquityValue, @ValuationNote) ON CONFLICT(DealId) DO UPDATE SET NetAssetValue=excluded.NetAssetValue, NetAssetNote=excluded.NetAssetNote, EBITDABase=excluded.EBITDABase, EBITDABaseYear=excluded.EBITDABaseYear, EBITDAMultiple=excluded.EBITDAMultiple, EBITDANetCashDebt=excluded.EBITDANetCashDebt, EBITDANote=excluded.EBITDANote, DCFDiscountRate=excluded.DCFDiscountRate, DCFTerminalGrowth=excluded.DCFTerminalGrowth, DCFEV=excluded.DCFEV, DCFNetCashDebt=excluded.DCFNetCashDebt, DCFNote=excluded.DCFNote, NOI=excluded.NOI, CapRate=excluded.CapRate, DirectNetCashDebt=excluded.DirectNetCashDebt, DirectNote=excluded.DirectNote, EBITDAEquityValue=excluded.EBITDAEquityValue, DCFEquityValue=excluded.DCFEquityValue, DirectEquityValue=excluded.DirectEquityValue, ValuationNote=excluded.ValuationNote;";
            using var cmd = new SqliteCommand(sql, conn);
            cmd.Parameters.AddWithValue("@DealId", v.DealId); cmd.Parameters.AddWithValue("@NetAssetNote", v.NetAssetNote); cmd.Parameters.AddWithValue("@EBITDABaseYear", v.EBITDABaseYear); cmd.Parameters.AddWithValue("@EBITDANote", v.EBITDANote); cmd.Parameters.AddWithValue("@DCFNote", v.DCFNote); cmd.Parameters.AddWithValue("@DirectNote", v.DirectNote); cmd.Parameters.AddWithValue("@ValuationNote", v.ValuationNote);
            DbHelperUtils.BindReal(cmd, "@NetAssetValue", v.NetAssetValue); DbHelperUtils.BindReal(cmd, "@EBITDABase", v.EBITDABase); DbHelperUtils.BindReal(cmd, "@EBITDAMultiple", v.EBITDAMultiple); DbHelperUtils.BindReal(cmd, "@EBITDANetCashDebt", v.EBITDANetCashDebt); DbHelperUtils.BindReal(cmd, "@DCFDiscountRate", v.DCFDiscountRate); DbHelperUtils.BindReal(cmd, "@DCFTerminalGrowth", v.DCFTerminalGrowth); DbHelperUtils.BindReal(cmd, "@DCFEV", v.DCFEV); DbHelperUtils.BindReal(cmd, "@DCFNetCashDebt", v.DCFNetCashDebt); DbHelperUtils.BindReal(cmd, "@NOI", v.NOI); DbHelperUtils.BindReal(cmd, "@CapRate", v.CapRate); DbHelperUtils.BindReal(cmd, "@DirectNetCashDebt", v.DirectNetCashDebt); DbHelperUtils.BindReal(cmd, "@EBITDAEquityValue", v.EBITDAEquityValue); DbHelperUtils.BindReal(cmd, "@DCFEquityValue", v.DCFEquityValue); DbHelperUtils.BindReal(cmd, "@DirectEquityValue", v.DirectEquityValue);
            cmd.ExecuteNonQuery();
        }

        private static CompanyProfile MapCompanyProfile(SqliteDataReader r) => new CompanyProfile { Id = r.GetInt64(r.GetOrdinal("Id")), DealId = r.GetInt64(r.GetOrdinal("DealId")), CompanyName = DbHelperUtils.StrD(r, "CompanyName"), CompanyNameSub = DbHelperUtils.StrD(r, "CompanyNameSub"), HeadOfficeAddress = DbHelperUtils.StrD(r, "HeadOfficeAddress"), FactoryAddress = DbHelperUtils.StrD(r, "FactoryAddress"), OtherOffice = DbHelperUtils.StrD(r, "OtherOffice"), Founded = DbHelperUtils.StrD(r, "Founded"), Founded2 = DbHelperUtils.StrD(r, "Founded2"), Capital = DbHelperUtils.StrD(r, "Capital"), RepresentativeName = DbHelperUtils.StrD(r, "RepresentativeName"), RepresentativeProfile = DbHelperUtils.StrD(r, "RepresentativeProfile"), ShareholderInfo = DbHelperUtils.StrD(r, "ShareholderInfo"), BusinessDetail = DbHelperUtils.StrD(r, "BusinessDetail"), Revenue = DbHelperUtils.StrD(r, "Revenue"), Employees = DbHelperUtils.StrD(r, "Employees"), MainClients = DbHelperUtils.StrD(r, "MainClients"), MainSuppliers = DbHelperUtils.StrD(r, "MainSuppliers"), Certifications = DbHelperUtils.StrD(r, "Certifications"), GroupCompanies = DbHelperUtils.StrD(r, "GroupCompanies"), TransferReason = DbHelperUtils.StrD(r, "TransferReason"), Remarks = DbHelperUtils.StrD(r, "Remarks") };
        private static FinancialHighlight MapFinancialHighlight(SqliteDataReader r) => new FinancialHighlight { Id = r.GetInt64(r.GetOrdinal("Id")), DealId = r.GetInt64(r.GetOrdinal("DealId")), PeriodType = DbHelperUtils.StrD(r, "PeriodType"), PeriodOrder = r.GetInt32(r.GetOrdinal("PeriodOrder")), PeriodLabel = DbHelperUtils.StrD(r, "PeriodLabel"), Revenue = DbHelperUtils.RealN(r, "Revenue"), CostRate = DbHelperUtils.RealN(r, "CostRate"), GrossProfit = DbHelperUtils.RealN(r, "GrossProfit"), GrossProfitRate = DbHelperUtils.RealN(r, "GrossProfitRate"), SGA = DbHelperUtils.RealN(r, "SGA"), OperatingProfit = DbHelperUtils.RealN(r, "OperatingProfit"), OperatingProfitRate = DbHelperUtils.RealN(r, "OperatingProfitRate"), OrdinaryProfit = DbHelperUtils.RealN(r, "OrdinaryProfit"), NetIncome = DbHelperUtils.RealN(r, "NetIncome"), EBITDA = DbHelperUtils.RealN(r, "EBITDA"), Depreciation = DbHelperUtils.RealN(r, "Depreciation"), CapEx = DbHelperUtils.RealN(r, "CapEx"), CurrentAssets = DbHelperUtils.RealN(r, "CurrentAssets"), CashEquivalents = DbHelperUtils.RealN(r, "CashEquivalents"), AccountsReceivable = DbHelperUtils.RealN(r, "AccountsReceivable"), Inventory = DbHelperUtils.RealN(r, "Inventory"), OtherCurrentAssets = DbHelperUtils.RealN(r, "OtherCurrentAssets"), FixedAssets = DbHelperUtils.RealN(r, "FixedAssets"), TotalAssets = DbHelperUtils.RealN(r, "TotalAssets"), CurrentLiabilities = DbHelperUtils.RealN(r, "CurrentLiabilities"), AccountsPayable = DbHelperUtils.RealN(r, "AccountsPayable"), ShortTermDebt = DbHelperUtils.RealN(r, "ShortTermDebt"), OtherCurrentLiabilities = DbHelperUtils.RealN(r, "OtherCurrentLiabilities"), FixedLiabilities = DbHelperUtils.RealN(r, "FixedLiabilities"), LongTermDebt = DbHelperUtils.RealN(r, "LongTermDebt"), OtherFixedLiabilities = DbHelperUtils.RealN(r, "OtherFixedLiabilities"), TotalLiabilities = DbHelperUtils.RealN(r, "TotalLiabilities"), NetAssets = DbHelperUtils.RealN(r, "NetAssets"), RetainedEarnings = DbHelperUtils.RealN(r, "RetainedEarnings") };
        private static ValuationData MapValuationData(SqliteDataReader r) => new ValuationData { Id = r.GetInt64(r.GetOrdinal("Id")), DealId = r.GetInt64(r.GetOrdinal("DealId")), NetAssetValue = DbHelperUtils.RealN(r, "NetAssetValue"), NetAssetNote = DbHelperUtils.StrD(r, "NetAssetNote"), EBITDABase = DbHelperUtils.RealN(r, "EBITDABase"), EBITDABaseYear = DbHelperUtils.StrD(r, "EBITDABaseYear"), EBITDAMultiple = DbHelperUtils.RealN(r, "EBITDAMultiple"), EBITDANetCashDebt = DbHelperUtils.RealN(r, "EBITDANetCashDebt"), EBITDANote = DbHelperUtils.StrD(r, "EBITDANote"), DCFDiscountRate = DbHelperUtils.RealN(r, "DCFDiscountRate"), DCFTerminalGrowth = DbHelperUtils.RealN(r, "DCFTerminalGrowth"), DCFEV = DbHelperUtils.RealN(r, "DCFEV"), DCFNetCashDebt = DbHelperUtils.RealN(r, "DCFNetCashDebt"), DCFNote = DbHelperUtils.StrD(r, "DCFNote"), NOI = DbHelperUtils.RealN(r, "NOI"), CapRate = DbHelperUtils.RealN(r, "CapRate"), DirectNetCashDebt = DbHelperUtils.RealN(r, "DirectNetCashDebt"), DirectNote = DbHelperUtils.StrD(r, "DirectNote"), EBITDAEquityValue = DbHelperUtils.RealN(r, "EBITDAEquityValue"), DCFEquityValue = DbHelperUtils.RealN(r, "DCFEquityValue"), DirectEquityValue = DbHelperUtils.RealN(r, "DirectEquityValue"), ValuationNote = DbHelperUtils.StrD(r, "ValuationNote") };

        private static void BindFinancialHighlight(SqliteCommand cmd, FinancialHighlight f)
        {
            cmd.Parameters.AddWithValue("@DealId", f.DealId); cmd.Parameters.AddWithValue("@PeriodType", f.PeriodType); cmd.Parameters.AddWithValue("@PeriodOrder", f.PeriodOrder); cmd.Parameters.AddWithValue("@PeriodLabel", f.PeriodLabel ?? "");
            DbHelperUtils.BindReal(cmd, "@Revenue", f.Revenue); DbHelperUtils.BindReal(cmd, "@CostRate", f.CostRate); DbHelperUtils.BindReal(cmd, "@GrossProfit", f.GrossProfit); DbHelperUtils.BindReal(cmd, "@GrossProfitRate", f.GrossProfitRate); DbHelperUtils.BindReal(cmd, "@SGA", f.SGA); DbHelperUtils.BindReal(cmd, "@OperatingProfit", f.OperatingProfit); DbHelperUtils.BindReal(cmd, "@OperatingProfitRate", f.OperatingProfitRate); DbHelperUtils.BindReal(cmd, "@OrdinaryProfit", f.OrdinaryProfit); DbHelperUtils.BindReal(cmd, "@NetIncome", f.NetIncome); DbHelperUtils.BindReal(cmd, "@EBITDA", f.EBITDA); DbHelperUtils.BindReal(cmd, "@Depreciation", f.Depreciation); DbHelperUtils.BindReal(cmd, "@CapEx", f.CapEx); DbHelperUtils.BindReal(cmd, "@CurrentAssets", f.CurrentAssets); DbHelperUtils.BindReal(cmd, "@CashEquivalents", f.CashEquivalents); DbHelperUtils.BindReal(cmd, "@AccountsReceivable", f.AccountsReceivable); DbHelperUtils.BindReal(cmd, "@Inventory", f.Inventory); DbHelperUtils.BindReal(cmd, "@OtherCurrentAssets", f.OtherCurrentAssets); DbHelperUtils.BindReal(cmd, "@FixedAssets", f.FixedAssets); DbHelperUtils.BindReal(cmd, "@TotalAssets", f.TotalAssets); DbHelperUtils.BindReal(cmd, "@CurrentLiabilities", f.CurrentLiabilities); DbHelperUtils.BindReal(cmd, "@AccountsPayable", f.AccountsPayable); DbHelperUtils.BindReal(cmd, "@ShortTermDebt", f.ShortTermDebt); DbHelperUtils.BindReal(cmd, "@OtherCurrentLiabilities", f.OtherCurrentLiabilities); DbHelperUtils.BindReal(cmd, "@FixedLiabilities", f.FixedLiabilities); DbHelperUtils.BindReal(cmd, "@LongTermDebt", f.LongTermDebt); DbHelperUtils.BindReal(cmd, "@OtherFixedLiabilities", f.OtherFixedLiabilities); DbHelperUtils.BindReal(cmd, "@TotalLiabilities", f.TotalLiabilities); DbHelperUtils.BindReal(cmd, "@NetAssets", f.NetAssets); DbHelperUtils.BindReal(cmd, "@RetainedEarnings", f.RetainedEarnings);
        }
    }
}